name: flash-sale-dev

x-common-volumes: &common-volumes
  - ./:/workspace
  # - ./.compose/volumes/.cache/.pnpm-store:/workspace/.pnpm-store
  # - ./.compose/volumes/.cache/node_modules/.root:/workspace/node_modules
  # - ./.compose/volumes/.cache/node_modules/common:/workspace/src/libs/common/node_modules
  # - ./.compose/volumes/.cache/node_modules/common-ui:/workspace/src/libs/common-ui/node_modules
  # - ./.compose/volumes/.cache/node_modules/backend:/workspace/src/apps/backend/node_modules
  # - ./.compose/volumes/.cache/node_modules/payment:/workspace/src/apps/payment/node_modules
  # - ./.compose/volumes/.cache/node_modules/frontend:/workspace/src/apps/frontend/node_modules

services:
  flsl-mongodb:
    image: mongo:7.0.14
    container_name: flsl-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./.compose/volumes/mongodb:/data
    restart: unless-stopped

  flsl-redis:
    image: redis:7.2.5
    container_name: flsl-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.compose/volumes/redis:/data
    restart: unless-stopped

  flsl-kafka:
    image: bitnami/kafka:3.7.0-debian-12-r8
    container_name: flsl-kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@flsl-kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://flsl-kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=false
    volumes:
      - ./.compose/volumes/kafka:/bitnami/kafka
    restart: unless-stopped

  flsl-kafkaui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: flsl-kafkaui
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=flsl-kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - flsl-kafka
    restart: unless-stopped

  flsl-libs:
    image: node:20.18.3-alpine
    container_name: flsl-libs
    working_dir: /workspace
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - CI=true
    volumes: *common-volumes
    command: sh -lc "npm i -g pnpm@10.9.0 && pnpm install && pnpm --filter common --filter common-ui build --watch"
    restart: unless-stopped

  flsl-backend:
    image: node:20.18.3-alpine
    container_name: flsl-backend
    working_dir: /workspace/src/apps/backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=1
      - CI=true
    volumes: *common-volumes
    command: sh -lc "npm i -g pnpm@10.9.0 && pnpm install && pnpm --filter backend start:dev"
    depends_on:
      - flsl-mongodb
      - flsl-redis
      - flsl-kafka
      - flsl-libs
    restart: unless-stopped

  flsl-payment:
    image: node:20.18.3-alpine
    container_name: flsl-payment
    working_dir: /workspace/src/apps/payment
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=1
      - CI=true
    volumes: *common-volumes
    command: sh -lc "npm i -g pnpm@10.9.0 && pnpm install && pnpm --filter payment start:dev"
    depends_on:
      - flsl-mongodb
      - flsl-redis
      - flsl-kafka
      - flsl-libs
    restart: unless-stopped

  flsl-frontend:
    image: node:20.18.3-alpine
    container_name: flsl-frontend
    working_dir: /workspace/src/apps/frontend
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PORT=3000
      - CI=true
    volumes: *common-volumes
    command: sh -lc "npm i -g pnpm@10.9.0 && pnpm install && pnpm --filter frontend dev"
    depends_on:
      - flsl-libs
    restart: unless-stopped

  flsl-kong:
    image: kong:3.7.1
    container_name: flsl-kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
    volumes:
      - ./.compose/volumes/kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - flsl-frontend
      - flsl-backend
      - flsl-payment
    restart: unless-stopped

networks:
  default:
    name: flash-sale-net
    driver: bridge
