packages:
  - src/**
  - '!**/test/**'

onlyBuiltDependencies:
  - '@nestjs/core'
  - sharp
  - unrs-resolver

catalogs:
  common:
    '@biomejs/biome': 2.2.0
    axios: ^1.11.0
    luxon: ^3.7.1
    bson: ^6.0.0
    uuid: ^9.0.1
    typescript: ^5
    rimraf: ^5.0.0
    '@types/uuid': ^9.0.0
  backend:
    '@nestjs/cli': ^11.0.0
    '@nestjs/common': ^11.0.1
    '@nestjs/core': ^11.0.1
    '@nestjs/platform-express': ^11.0.1
    '@nestjs/schematics': ^11.0.0
    '@nestjs/testing': ^11.0.1
    '@types/express': ^5.0.0
    '@types/jest': ^30.0.0
    '@types/luxon': ^3.7.1
    '@types/node': ^22.10.7
    '@types/supertest': ^6.0.2
    jest: ^30.0.0
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.1
    source-map-support: ^0.5.21
    supertest: ^7.0.0
    ts-jest: ^29.2.5
    ts-loader: ^9.5.2
    ts-node: ^10.9.2
    tsconfig-paths: ^4.2.0
    typescript: ^5.7.3
  frontend:
    '@emotion/react': ^11.14.0
    '@emotion/styled': ^11.14.1
    '@mui/icons-material': ^7.3.1
    '@mui/material': ^7.3.1
    '@mui/material-nextjs': ^7.3.0
    '@mantine/hooks': ^7.15.3
    next: 15.5.0
    react: 19.1.0
    react-dom: 19.1.0
    '@types/luxon': ^3.7.1
    '@types/node': ^20
    '@types/react': ^19
    '@types/react-dom': ^19
    typescript: ^5
